global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Collector의 prometheus exporter(8889) 긁기
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  # 앱이 직접 노출하는 /actuator/prometheus 긁기
  - job_name: "todo-app"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["todo-app:8080"]
